### ISSUE TITLE
Introduce Valkyrie before missions

### ISSUE THREAD

**Issue by andypbarrett** [nsidc/NSIDC-Data-Tutorials#4]
It think it is better to introduce Valkyrie and the problems it solves before giving an overview of the missions.  For example...

## Why Valkyrie

In 2003, NASA launched the Ice, Cloud and Land Elevation Satellite (ICESat) mission.  Over the following six years, ICESat collected valuable data about ice thickness in the Polar Regions.  Unfortunately, the ICESat mission ended before a follow-on mission could be launched.  To fill the gap, an airborne campaign called Operation IceBridge was started.  Between 2009 and 2019, Operation IceBridge flew numerous campaigns over the Greenland and Antarctic icesheets, as well as over sea ice in the Arctic and Southern Oceans.  The last campaign was __fill in date here__.  In September 2018, ICESat-2 was launched to continue NASA's collecting ice, cloud and land elevation data.

The wealth of data from these three missions, as well as from earlier missions, presents an opportunity to measure the evolution of ice thickness over several decades.  However, combining data from these missions is a challenge.  Data from the Airborne Topographic Mapper (ATM) flown during IceBridge campaigns is store in __N__ different formats.  ICESat and ICESat-2 data are also in different file formats.  Data needs to be harmonized (put into similar formats) before comparisons can be made.  A further complication is that the coordinate reference systems used to locate measurements have changed.  The Earth's surface is not static and changes shape.  To account for these changes, terrestrial reference frames that relate latitude and longitude to points on the Earth are updated on a regular basis.  Since the launch of ICESat, the International Terrestrial Reference Frame has been updated three times.  The geolocation accuracy of instruments means that a point measured at the beginning of the record is not the same point as that measured at the end of the record.  Even though the latitude and longitude is the same.  These changes in geolocation need to be reconciled if meaningful comparisons of measurements are to be made.

Valkyrie solves this problem...

__This needs some work__

## Brief Overview of ICESat-2

**Comment by asteiker** [comment]
This was updated prior to our advertisement of Iceflow last year.
