### ISSUE TITLE
Prefer some other term than "holistic"

### ISSUE THREAD

**Issue by andypbarrett** [nsidc/NSIDC-Data-Tutorials#5]
I'm not sure what is meant by "holistic".  Maybe "use together", "combine", "compare"

**Comment by asteiker** [comment]
This was updated prior to our initial advertisement of Iceflow (I don't see "holistic" in https://github.com/nsidc/NSIDC-Data-Tutorials/blob/main/notebooks/iceflow/0_introduction.ipynb).
